on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


name: build

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    container: archlinux:latest    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: pacman -Syu base-devel git --noconfirm --overwrite '*' && sed -i '/E_ROOT/d' /usr/bin/makepkg && /usr/bin/makepkg  -sf --noconfirm
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aws-dyndns
          path: *.zst
